# Generated by Django 3.1.3 on 2023-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_choice_correct',
            field=models.BooleanField(default=False),
        ),
    ]
