# Generated by Django 3.1.3 on 2023-04-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_auto_20230415_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_choice_correct',
            new_name='is_correct',
        ),
    ]
